version: "3"

services:
  app:
    container_name: tinkoff-acquiring-client
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - default